### ISSUE TITLE
The script hang indefinitely

### ISSUE THREAD

**Issue by jyhhuah-cynopsis** [in3rsha/bitcoin-to-neo4j#11]
### Issue Description
The PHP script main.php consider the blockchain file BLK01210.dat is incomplete and stop processing

### Expected Behavior
The blk01210.dat is expected to be correct and the PHP script suppose to process it without issue. (i have done some checking manually and cross check with the content with bitcoin.info website to confirm the content is correct)

### Which line of Code causing the issue
main.php, line 109
`if (hexdec(substr($block, -78)) == 0) {
                        echo "Doesn't look like the blk.dat file has all the bytes of data for the block. Wait a second for it to arrive...\n";`

The comment says: **if last 78 characters are all zeros, then we probably haven't got the full block data, so wait for it*

### My Environment
PHP version: PHP version: 7.1.16
Neo4j version: {
  "edition" : "community",
  "version" : "3.4.7"
}

### Procedures to Reproduce the Issue
To make it simple to reproduce the issue, i have modified the main.php to remove the redis and neo4j issue as they are not relevant, and focus on the reading logic from the blockchain file

https://gist.github.com/jyhhuah-cynopsis/82151b3af6c6845a61898b9ce0480eab/

1. download the test.php from github link above
2. download the BLK01210.dat file (this is the raw data file from bitcoin blockchain)
3. run the test.php  e.g. php test.php

you should be able to see the php script was able to read the content until it stop and complain the file is incomplete, due to last 78 bytes are all zeros.

### Procedures to Identify the Block content is correct
1. download the test-show-block-content.php from the github link above
2. run the php script, where it will stop at the block content that seems to incomplete for php script. and print out the content of the block and the details of the block.
`version  536870912
 prevBlock   00000000000000000023bbd4a2cbc9857a78a8cee1ca68887abd5eadb8105478
  merkleroot  9db133d724983e68b1fa87da585e4396ff5adfa7b0f6aeb448cf34f2d3f6f579
 timestamp   1521094427
 : 0000000000000000004eb4bffffd6cb0fca4b8b9bc8941c5e3ad2eab432fe1dd [114.08 kb] (fp:)`

From the print out we can see the PHP is acting correct as the block content really end with zeroes.
Also we can identify the blockhash of this block is 0000000000000000004eb4bffffd6cb0fca4b8b9bc8941c5e3ad2eab432fe1dd

3. Next, we can check the content of this block from bitcoin.info
https://blockchain.info/rawblock/0000000000000000004eb4bffffd6cb0fca4b8b9bc8941c5e3ad2eab432fe1dd?format=hex

where we can see the content really end with lot of zeros.
This is the reason why i am so sure the content of blk01210.dat is correct.

**Comment by in3rsha** [comment]
Hi there,

Excellent bug report, and good find. Your analysis is exactly correct.

I ran in to this issue on my own personal version of this script but forgot to update this GitHub repo, so thank you for letting me know about this.

**Quick Fix:**

I have updated the check to look at the last **500 characters** of the block to see if they are equal to zero (instead of **78 characters**) to help determine whether we have got an incomplete block or not.

If you pull my latest change, the script will import the block without an issue. I have been running the script continuously with this simple change and have not ran in to any problems so far.

**Why did this bug happen?**

The script reads block data from the blk.dat files. I wanted the script to check we did indeed have complete block data before decoding it and importing it in to Neo4j (in the event that a new block is written to the file and we try to read it before it is fully written to the file).

For some reason, my "check" involved converting the last 78 hex characters of a block in to decimal, and if it was zero then I assumed the block was incomplete, as I didn't believe any transaction would have 78 zeros at the end of it.

However, thanks to [Segwit](http://learnmeabitcoin.com/faq/segregated-witness) (and the witness data section of a transaction), it's not completely unlikely that a transaction can have a bunch of zeros at the end. This happens when we have a segwit transaction and the majority of the inputs do not make use of the witness data, so each input sets their witness to `00`.

You can see this by looking at the serialized data of the offending transaction here: [eb23752e297c59bf71f4280be9200284630b4037a2dbe083813fdd990a1987ec](http://learnmeabitcoin.com/browser/transaction/eb23752e297c59bf71f4280be9200284630b4037a2dbe083813fdd990a1987ec)

So, seeing as this was the **last** transaction in the block, the block ends up having 78 zeros at the end, and my script thought it was reading an incomplete block of data.

**Note**

There's probably a better fix for checking whether we have a complete block of data (i.e. the script has been able to read the expected number of bytes from the file).
